server:
  port: 9070
  servlet:
    context-path:

spring:
  application:
    name: demo-vending-machine
  datasource:
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    url: jdbc:h2:mem:testdbvm
    driver-class-name: org.h2.Driver
    username: test
    password: vm1234
  h2:
    console:
      settings:
        web-allow-others: true
        trace: true
      enabled: true
      path: /h2-console
